# Generated by Django 4.2.2 on 2023-08-12 08:26

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Название')),
                ('title_ru', models.CharField(max_length=100, null=True, verbose_name='Название')),
                ('title_en', models.CharField(max_length=100, null=True, verbose_name='Название')),
                ('product_image_1', models.ImageField(upload_to='product_photos', verbose_name='Фото_1_к_товару')),
                ('product_image_2', models.ImageField(blank=True, upload_to='product_photos', verbose_name='Фото_2_к_товару')),
                ('product_image_3', models.ImageField(blank=True, upload_to='product_photos', verbose_name='Фото_3_к_товару')),
                ('product_image_4', models.ImageField(blank=True, upload_to='product_photos', verbose_name='Фото_4_к_товару')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('description_ru', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('description_en', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('price', models.IntegerField(blank=True, null=True, verbose_name='Цена')),
            ],
            options={
                'verbose_name': 'Товар',
                'verbose_name_plural': 'Товары',
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='user')),
                ('title_ru', models.CharField(max_length=50, null=True, verbose_name='user')),
                ('title_en', models.CharField(max_length=50, null=True, verbose_name='user')),
                ('way', models.CharField(max_length=50, verbose_name='Маршрут')),
                ('way_ru', models.CharField(max_length=50, null=True, verbose_name='Маршрут')),
                ('way_en', models.CharField(max_length=50, null=True, verbose_name='Маршрут')),
                ('content', models.TextField(verbose_name='Отзыв')),
                ('content_ru', models.TextField(null=True, verbose_name='Отзыв')),
                ('content_en', models.TextField(null=True, verbose_name='Отзыв')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Дата')),
                ('answer', models.TextField(blank=True, verbose_name='Ответ')),
                ('answer_ru', models.TextField(blank=True, null=True, verbose_name='Ответ')),
                ('answer_en', models.TextField(blank=True, null=True, verbose_name='Ответ')),
                ('moderation', models.BooleanField(default=False, verbose_name='Модерация')),
            ],
            options={
                'verbose_name': 'Отзыв',
                'verbose_name_plural': 'Отзывы',
            },
        ),
        migrations.CreateModel(
            name='VideoReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Заголовок')),
                ('title_ru', models.CharField(max_length=100, null=True, verbose_name='Заголовок')),
                ('title_en', models.CharField(max_length=100, null=True, verbose_name='Заголовок')),
                ('title_image', models.ImageField(blank=True, upload_to='cargo_media', verbose_name='Фото к заголовку')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('description_ru', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('description_en', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('video', models.FileField(upload_to='video', verbose_name='Видео')),
                ('create_at_date', models.DateTimeField(auto_now_add=True, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['mp4'])], verbose_name='Дата')),
                ('addit_image_1', models.ImageField(blank=True, upload_to='reports_photos', verbose_name='Фото_1 к отчету')),
                ('addit_image_2', models.ImageField(blank=True, upload_to='reports_photos', verbose_name='Фото_2 к отчету')),
                ('addit_image_3', models.ImageField(blank=True, upload_to='reports_photos', verbose_name='Фото_3 к отчету')),
                ('addit_image_4', models.ImageField(blank=True, upload_to='reports_photos', verbose_name='Фото_4 к отчету')),
            ],
            options={
                'verbose_name': 'Видеоотчет',
                'verbose_name_plural': 'Видеоотчеты',
            },
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.FileField(blank=True, null=True, upload_to='cargo_media', verbose_name='Фото')),
                ('name', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='Cargo.review')),
            ],
            options={
                'verbose_name': 'Фото',
                'verbose_name_plural': 'Фотографии',
            },
        ),
    ]
